[package]
name = "normalduck/node"
version = "0.1.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = [".vscode", ".vscode/**", "build", "build/**", "default.project.json"]
include = ["init.lua", "wally.lock", "wally.toml"]

[dependencies]
Promise = "evaera/promise@4.0.0"
